//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCopyright("Copyright © 2015–2017 Scott McDonald")]
[assembly: System.Reflection.AssemblyVersion("1.2.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.2.1.12")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.2.1-beta")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCopyright = "Copyright © 2015–2017 Scott McDonald";
    
    internal const string AssemblyVersion = "1.2.0.0";
    
    internal const string AssemblyFileVersion = "1.2.1.12";
    
    internal const string AssemblyInformationalVersion = "1.2.1-beta";
    
    private ThisAssembly() {
    }
}
