//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonApiFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonApiFramework.Properties.CoreErrorStrings", typeof(CoreErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Read Error.
        /// </summary>
        internal static string JsonReadErrorTitle {
            get {
                return ResourceManager.GetString("JsonReadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find link for the rel={0}..
        /// </summary>
        internal static string LinkNotFoundMessage {
            get {
                return ResourceManager.GetString("LinkNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deserialize {0}, error with {1}..
        /// </summary>
        internal static string MetadataDeserializationExceptionInvalidJsonDetail {
            get {
                return ResourceManager.GetString("MetadataDeserializationExceptionInvalidJsonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Deserialization Error.
        /// </summary>
        internal static string MetadataDeserializationExceptionTitle {
            get {
                return ResourceManager.GetString("MetadataDeserializationExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has {1} already configured. Ensure {1} is configured only once..
        /// </summary>
        internal static string MetadataExceptionAlreadyConfiguredDetail {
            get {
                return ResourceManager.GetString("MetadataExceptionAlreadyConfiguredDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has missing {1} metadata. Ensure metadata is configured correctly for the respective domain/schema..
        /// </summary>
        internal static string MetadataExceptionMissingMetadataDetail {
            get {
                return ResourceManager.GetString("MetadataExceptionMissingMetadataDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is missing required {1} configuration. Ensure {1} is configured because it is required..
        /// </summary>
        internal static string MetadataExceptionMissingRequiredConfigurationDetail {
            get {
                return ResourceManager.GetString("MetadataExceptionMissingRequiredConfigurationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Error.
        /// </summary>
        internal static string MetadataExceptionTitle {
            get {
                return ResourceManager.GetString("MetadataExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find relationship for the rel={0}..
        /// </summary>
        internal static string RelationshipNotFoundMessage {
            get {
                return ResourceManager.GetString("RelationshipNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} node has already been added to a tree..
        /// </summary>
        internal static string TreeExceptionNodeAlreadyAddedMessage {
            get {
                return ResourceManager.GetString("TreeExceptionNodeAlreadyAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attribute has already been added to a node..
        /// </summary>
        internal static string TreeExceptionNodeAttributeAlreadyAddedMessage {
            get {
                return ResourceManager.GetString("TreeExceptionNodeAttributeAlreadyAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert from object {0} of type {1} to type {2}..
        /// </summary>
        internal static string TypeConverterExceptionMessage {
            get {
                return ResourceManager.GetString("TypeConverterExceptionMessage", resourceCulture);
            }
        }
    }
}
