//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonApiFramework {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonApiFramework.Properties.CoreErrorStrings", typeof(CoreErrorStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add an attribute to a read-only DOM node [type={0}]..
        /// </summary>
        internal static string DomExceptionDetailReadOnlyNodeUnableToAddAttribute {
            get {
                return ResourceManager.GetString("DomExceptionDetailReadOnlyNodeUnableToAddAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add attributes to a read-only DOM node [type={0}]..
        /// </summary>
        internal static string DomExceptionDetailReadOnlyNodeUnableToAddAttributes {
            get {
                return ResourceManager.GetString("DomExceptionDetailReadOnlyNodeUnableToAddAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add a DOM node to a read-only DOM node [type={0}]..
        /// </summary>
        internal static string DomExceptionDetailReadOnlyNodeUnableToAddNode {
            get {
                return ResourceManager.GetString("DomExceptionDetailReadOnlyNodeUnableToAddNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add DOM nodes to a read-only DOM node [type={0}]..
        /// </summary>
        internal static string DomExceptionDetailReadOnlyNodeUnableToAddNodes {
            get {
                return ResourceManager.GetString("DomExceptionDetailReadOnlyNodeUnableToAddNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove an attribute from a read-only DOM node [type={0}]..
        /// </summary>
        internal static string DomExceptionDetailReadOnlyNodeUnableToRemoveAttribute {
            get {
                return ResourceManager.GetString("DomExceptionDetailReadOnlyNodeUnableToRemoveAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove a DOM node from a read-only DOM node [type={0}]..
        /// </summary>
        internal static string DomExceptionDetailReadOnlyNodeUnableToRemoveNode {
            get {
                return ResourceManager.GetString("DomExceptionDetailReadOnlyNodeUnableToRemoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to replace an attribute from a read-only DOM node [type={0}]..
        /// </summary>
        internal static string DomExceptionDetailReadOnlyNodeUnableToReplaceAttribute {
            get {
                return ResourceManager.GetString("DomExceptionDetailReadOnlyNodeUnableToReplaceAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to replace a DOM node from a read-only DOM node [type={0}]..
        /// </summary>
        internal static string DomExceptionDetailReadOnlyNodeUnableToReplaceNode {
            get {
                return ResourceManager.GetString("DomExceptionDetailReadOnlyNodeUnableToReplaceNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal DOM Error.
        /// </summary>
        internal static string DomExceptionTitle {
            get {
                return ResourceManager.GetString("DomExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find link for the rel={0}..
        /// </summary>
        internal static string LinksLinkNotFoundDetail {
            get {
                return ResourceManager.GetString("LinksLinkNotFoundDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Not Found.
        /// </summary>
        internal static string LinksLinkNotFoundTitle {
            get {
                return ResourceManager.GetString("LinksLinkNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} node has already been added to a tree..
        /// </summary>
        internal static string TreeExceptionNodeAlreadyAddedMessage {
            get {
                return ResourceManager.GetString("TreeExceptionNodeAlreadyAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attribute has already been added to a node..
        /// </summary>
        internal static string TreeExceptionNodeAttributeAlreadyAddedMessage {
            get {
                return ResourceManager.GetString("TreeExceptionNodeAttributeAlreadyAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert from object {0} of type {1} to type {2}..
        /// </summary>
        internal static string TypeConverterExceptionMessage {
            get {
                return ResourceManager.GetString("TypeConverterExceptionMessage", resourceCulture);
            }
        }
    }
}
