//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonApiFramework {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonApiFramework.Properties.CoreErrorStrings", typeof(CoreErrorStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read or write the \&quot;data\&quot; member, not a document that contains a \&quot;data\&quot; member as an array of resources..
        /// </summary>
        internal static string DocumentDoesNotContainDataMemberAsResourceCollectionDetail {
            get {
                return ResourceManager.GetString("DocumentDoesNotContainDataMemberAsResourceCollectionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read or write the \&quot;data\&quot; member, not a document that contains a \&quot;data\&quot; member as a single resource..
        /// </summary>
        internal static string DocumentDoesNotContainDataMemberAsResourceDetail {
            get {
                return ResourceManager.GetString("DocumentDoesNotContainDataMemberAsResourceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read or write the \&quot;data\&quot; member, not a document that contains a \&quot;data\&quot; member as an array of resource identifiers..
        /// </summary>
        internal static string DocumentDoesNotContainDataMemberAsResourceIdentifierCollectionDetail {
            get {
                return ResourceManager.GetString("DocumentDoesNotContainDataMemberAsResourceIdentifierCollectionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read or write the \&quot;data\&quot; member, not a document that contains a \&quot;data\&quot; member as a single resource identifier..
        /// </summary>
        internal static string DocumentDoesNotContainDataMemberAsResourceIdentifierDetail {
            get {
                return ResourceManager.GetString("DocumentDoesNotContainDataMemberAsResourceIdentifierDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read or write the \&quot;data\&quot; member, not a document that contains a \&quot;data\&quot; member..
        /// </summary>
        internal static string DocumentDoesNotContainDataMemberDetail {
            get {
                return ResourceManager.GetString("DocumentDoesNotContainDataMemberDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read or write the \&quot;errors\&quot; member, not a document that contains an \&quot;errors\&quot; member..
        /// </summary>
        internal static string DocumentDoesNotContainErrorsMemberDetail {
            get {
                return ResourceManager.GetString("DocumentDoesNotContainErrorsMemberDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read or write the \&quot;included\&quot; member, not a document that contains an \&quot;included\&quot; member..
        /// </summary>
        internal static string DocumentDoesNotContainIncludedMemberDetail {
            get {
                return ResourceManager.GetString("DocumentDoesNotContainIncludedMemberDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an Errors Document.
        /// </summary>
        internal static string DocumentNotErrorsDocumentTitle {
            get {
                return ResourceManager.GetString("DocumentNotErrorsDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a Resource Collection Document.
        /// </summary>
        internal static string DocumentNotResourceCollectionDocumentTitle {
            get {
                return ResourceManager.GetString("DocumentNotResourceCollectionDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a Resource Document.
        /// </summary>
        internal static string DocumentNotResourceDocumentTitle {
            get {
                return ResourceManager.GetString("DocumentNotResourceDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a Resource Identifier Collection Document.
        /// </summary>
        internal static string DocumentNotResourceIdentifierCollectionDocumentTitle {
            get {
                return ResourceManager.GetString("DocumentNotResourceIdentifierCollectionDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a Resource Identifier Document.
        /// </summary>
        internal static string DocumentNotResourceIdentifierDocumentTitle {
            get {
                return ResourceManager.GetString("DocumentNotResourceIdentifierDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a Resource Oriented Document.
        /// </summary>
        internal static string DocumentNotResourceOrientedDocumentTitle {
            get {
                return ResourceManager.GetString("DocumentNotResourceOrientedDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a Resource Document or Resource Collection Document.
        /// </summary>
        internal static string DocumentNotResourceOrResourceCollectionDocumentTitle {
            get {
                return ResourceManager.GetString("DocumentNotResourceOrResourceCollectionDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document can not contain both \&quot;{0}\&quot; and \&quot;{1}\&quot; members..
        /// </summary>
        internal static string JsonApiDocumentCanNotContainBothMembersDetail {
            get {
                return ResourceManager.GetString("JsonApiDocumentCanNotContainBothMembersDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document contains an illegal \&quot;{0}\&quot; member. Member should be an array..
        /// </summary>
        internal static string JsonApiDocumentContainsIllegalMemberMemberShouldBeAnArrayDetail {
            get {
                return ResourceManager.GetString("JsonApiDocumentContainsIllegalMemberMemberShouldBeAnArrayDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document contains an illegal \&quot;{0}\&quot; member. Member should be null, an object, or an array..
        /// </summary>
        internal static string JsonApiDocumentContainsIllegalMemberMemberShouldBeNullAnObjectOrAnArrayDetail {
            get {
                return ResourceManager.GetString("JsonApiDocumentContainsIllegalMemberMemberShouldBeNullAnObjectOrAnArrayDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document contains a hetergenous collection of Resources and ResourceIdentifiers, must be a homogenous collection of either Resources or ResourceIdentifiers..
        /// </summary>
        internal static string JsonApiDocumentMustContainHetergenousCollectionOrResourcesOrResourceIdentifiersDetail {
            get {
                return ResourceManager.GetString("JsonApiDocumentMustContainHetergenousCollectionOrResourcesOrResourceIdentifiersDe" +
                        "tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JsonApi Error.
        /// </summary>
        internal static string JsonApiErrorTitle {
            get {
                return ResourceManager.GetString("JsonApiErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON \&quot;{0}\&quot; for either a Resource or ResourceIdentifier..
        /// </summary>
        internal static string JsonTextContainsInvalidJsonForResourceOrResourceIdentifierDetail {
            get {
                return ResourceManager.GetString("JsonTextContainsInvalidJsonForResourceOrResourceIdentifierDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON.
        /// </summary>
        internal static string JsonTextContainsInvalidJsonTitle {
            get {
                return ResourceManager.GetString("JsonTextContainsInvalidJsonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find link for the rel={0}..
        /// </summary>
        internal static string LinksLinkNotFoundDetail {
            get {
                return ResourceManager.GetString("LinksLinkNotFoundDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Not Found.
        /// </summary>
        internal static string LinksLinkNotFoundTitle {
            get {
                return ResourceManager.GetString("LinksLinkNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read or write the \&quot;data\&quot; member, not a relationship that contains a \&quot;data\&quot; member as an array of resource identifiers..
        /// </summary>
        internal static string RelationshipDoesNotContainDataMemberAsResourceIdentifierCollectionDetail {
            get {
                return ResourceManager.GetString("RelationshipDoesNotContainDataMemberAsResourceIdentifierCollectionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read or write the \&quot;data\&quot; member, not a relationship that contains a \&quot;data\&quot; member as a single resource identifier..
        /// </summary>
        internal static string RelationshipDoesNotContainDataMemberAsResourceIdentifierDetail {
            get {
                return ResourceManager.GetString("RelationshipDoesNotContainDataMemberAsResourceIdentifierDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a ToManyRelationship.
        /// </summary>
        internal static string RelationshipNotToManyRelatioshipTitle {
            get {
                return ResourceManager.GetString("RelationshipNotToManyRelatioshipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a ToOneRelationship.
        /// </summary>
        internal static string RelationshipNotToOneRelatioshipTitle {
            get {
                return ResourceManager.GetString("RelationshipNotToOneRelatioshipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find relationship for the rel={0}..
        /// </summary>
        internal static string RelationshipsRelationshipNotFoundDetail {
            get {
                return ResourceManager.GetString("RelationshipsRelationshipNotFoundDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Not Found.
        /// </summary>
        internal static string RelationshipsRelationshipNotFoundTitle {
            get {
                return ResourceManager.GetString("RelationshipsRelationshipNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has missing {1} metadata. Ensure metadata is configured correctly for the respective domain/schema..
        /// </summary>
        internal static string ServiceModelExceptionDetailMissingMetadata {
            get {
                return ResourceManager.GetString("ServiceModelExceptionDetailMissingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceModel Error.
        /// </summary>
        internal static string ServiceModelExceptionTitle {
            get {
                return ResourceManager.GetString("ServiceModelExceptionTitle", resourceCulture);
            }
        }
    }
}
