//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonApiFramework.Server {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServerErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonApiFramework.Server.Properties.ServerErrorStrings", typeof(ServerErrorStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to build &apos;{0}&apos; for a single json:api document with a collection of &apos;{0}&apos; objects..
        /// </summary>
        internal static string DocumentBuildExceptionDetailBuildDocumentWithCollectionOfObjects {
            get {
                return ResourceManager.GetString("DocumentBuildExceptionDetailBuildDocumentWithCollectionOfObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to build json:api &apos;{0}&apos; relationship [rel={1}], the &apos;{0}&apos; resource linkage was not built correctly in the json:api document..
        /// </summary>
        internal static string DocumentBuildExceptionDetailBuildIncorrectResourceLinkage {
            get {
                return ResourceManager.GetString("DocumentBuildExceptionDetailBuildIncorrectResourceLinkage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to build &apos;{0}&apos; for a collection [count={1}] of json:api links [rel={2}] with a collection [count={3}] of &apos;{0}&apos; objects, collection counts mismatch. Make sure the collection counts are the same..
        /// </summary>
        internal static string DocumentBuildExceptionDetailBuildLinkCollectionCountMismatch {
            get {
                return ResourceManager.GetString("DocumentBuildExceptionDetailBuildLinkCollectionCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to build &apos;{0}&apos; for a single json:api link [rel={1}] with a collection of &apos;{0}&apos; objects..
        /// </summary>
        internal static string DocumentBuildExceptionDetailBuildLinkWithCollectionOfObjects {
            get {
                return ResourceManager.GetString("DocumentBuildExceptionDetailBuildLinkWithCollectionOfObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to build a non-standard json:api link [rel={0}] for json:api document. Create a derived hypermedia assembler to create this non-standard json:api document link [rel={0}]..
        /// </summary>
        internal static string DocumentBuildExceptionDetailBuildNonStandardDocumentLink {
            get {
                return ResourceManager.GetString("DocumentBuildExceptionDetailBuildNonStandardDocumentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to build a non-standard json:api link [rel={0}] for CLR resource [type={1}] . Create a derived hypermedia assembler to create this non-standard json:api resource link [rel={0}]..
        /// </summary>
        internal static string DocumentBuildExceptionDetailBuildNonStandardResourceLink {
            get {
                return ResourceManager.GetString("DocumentBuildExceptionDetailBuildNonStandardResourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to build &apos;{0}&apos; for a collection [count={1}] of json:api relationships [rel={2}] with a collection [count={3}] of &apos;{0}&apos; objects, collection counts mismatch. Make sure the collection counts are the same..
        /// </summary>
        internal static string DocumentBuildExceptionDetailBuildRelationshipCollectionCountMismatch {
            get {
                return ResourceManager.GetString("DocumentBuildExceptionDetailBuildRelationshipCollectionCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to build &apos;{0}&apos; for a collection of json:api relationship [rel={1}] with a single &apos;{0}&apos; object..
        /// </summary>
        internal static string DocumentBuildExceptionDetailBuildRelationshipCollectionWithSingleObject {
            get {
                return ResourceManager.GetString("DocumentBuildExceptionDetailBuildRelationshipCollectionWithSingleObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to build &apos;{0}&apos; for a single json:api relationship [rel={1}] with a collection of &apos;{0}&apos; objects..
        /// </summary>
        internal static string DocumentBuildExceptionDetailBuildRelationshipWithCollectionOfObjects {
            get {
                return ResourceManager.GetString("DocumentBuildExceptionDetailBuildRelationshipWithCollectionOfObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create json:api relationship [rel={0}] from CLR resource [type={1} to CLR resource [type={2}], relationship cardinality mismatch between built document [value={3}] and service model schema [value={4}]..
        /// </summary>
        internal static string DocumentBuildExceptionDetailBuildResourceRelationshipCardinalityMismatch {
            get {
                return ResourceManager.GetString("DocumentBuildExceptionDetailBuildResourceRelationshipCardinalityMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The read-write DOM node [type={0}] has unexpected read-only child DOM node [type={1}]..
        /// </summary>
        internal static string DomExceptionDetailReadWriteNodeHasUnexpectedReadOnlyChildNode {
            get {
                return ResourceManager.GetString("DomExceptionDetailReadWriteNodeHasUnexpectedReadOnlyChildNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected collection count mismatch between {0} [count={1}] and {2} [count={3}]..
        /// </summary>
        internal static string InternalErrorExceptionDetailCollectionCountMismatch {
            get {
                return ResourceManager.GetString("InternalErrorExceptionDetailCollectionCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get a hypermedia assembler, exceeded internal size limit of &apos;{0}&apos; for hypermedia paths..
        /// </summary>
        internal static string InternalErrorExceptionDetailExceededHypermediaPathSizeLimit {
            get {
                return ResourceManager.GetString("InternalErrorExceptionDetailExceededHypermediaPathSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the CLR resource type for  hypermedia path [type={0}]..
        /// </summary>
        internal static string InternalErrorExceptionDetailInvalidGetClrResourceTypeForHypermediaPath {
            get {
                return ResourceManager.GetString("InternalErrorExceptionDetailInvalidGetClrResourceTypeForHypermediaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize the hypermedia assembler registry, unknown hypermedia assembler [name={0}] parameter..
        /// </summary>
        internal static string InternalErrorExceptionDetailUnknownHypermediaAssembler {
            get {
                return ResourceManager.GetString("InternalErrorExceptionDetailUnknownHypermediaAssembler", resourceCulture);
            }
        }
    }
}
